name:                egison-haskell
version:             0.1.0.0
github:              "egison/egison-haskell"
license:             MIT
author:              "kotapiku, Satoshi Egi"
maintainer:          "Satoshi Egi <egi@egison.org>"
copyright:           "2019, kotapiku"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/egison/egison-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - Useful
  - containers
  - template-haskell
  - haskell-src-meta
  - strings
  - regex-compat

tests:
  egison-haskell-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egison-haskell
    - hspec
    - primes
